language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - pip install -r testrequirements.txt

install:
  - pip install -e .

# command to run tests
script:
  - nosetests --with-coverage --cover-package=fs tests
