language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

os:
  - linux
  - osx

before_install:
  - pip install -r testrequirements.txt

install:
  - pip install -e .

after_success:
  - coveralls

# command to run tests
script:
  - nosetests --with-coverage --cover-package=fs tests
